image:
  file: .gitpod.Dockerfile
tasks:
  - name: main-console
    command: |
      clear
  - name: setup
    before: |
      # REMOVE USER VALIDATION -Y ON JAVA 8 INSTALLATION
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config
      
      # JAVA 8 INSTALL
      sdk install java 8.0.372-amzn

      # "use" Java 8
      sdk use java 8.0.372-amzn

      # download DSE
      curl -OL https://downloads.datastax.com/enterprise/dse-6.8.tar.gz

      #create /var/log and /var/lib cassandra ahead of time!
      sudo mkdir /var/log/cassandra
      sudo mkdir /var/lib/cassandra

      #set ownership to gitpod user
      sudo chown -R gitpod:gitpod /var/lib/cassandra/
      sudo chown -R gitpod:gitpod /var/log/cassandra/

      #set permissions
      sudo chmod 750 /var/log/cassandra
      sudo chmod 750 /var/lib/cassandra

    command: |
      gp open README.md
      unset JAVA_TOOL_OPTIONS
ports:
  - port: 8888
    onOpen: open-preview
  - port: 8080
    visibility: public
    onOpen: open-browser
